// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CVSS c v s s
//
// swagger:model CVSS
type CVSS struct {

	// The CVSS-2 score for the vulnerability
	ScoreV2 *float64 `json:"score_v2,omitempty"`

	// The CVSS-3 score for the vulnerability/
	ScoreV3 *float64 `json:"score_v3,omitempty"`

	// The CVSS-2 attack vector.
	VectorV2 string `json:"vector_v2,omitempty"`

	// The CVSS-3 attack vector.
	VectorV3 string `json:"vector_v3,omitempty"`
}

// Validate validates this c v s s
func (m *CVSS) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CVSS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CVSS) UnmarshalBinary(b []byte) error {
	var res CVSS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
